flags: {}
packages:
- '.'
- location: ../Nomyx-Core
  extra-dep: true
- location: ../Nomyx-Language
  extra-dep: true
- location: ../Nomyx-Library
  extra-dep: true
- location: ../shortcut
  extra-dep: true
- location: ../Imprevu
  extra-dep: true
extra-deps:
- DebugTraceHelpers-0.12
- time-recurrence-0.9.2
resolver: lts-5.11
